package com.example.Auction_System.controller;

import com.example.Auction_System.dto.OrderResponseDTO;
import com.example.Auction_System.service.OrderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/orders")
@CrossOrigin(origins = "*") // Allows your frontend (e.g., React) to communicate smoothly with these endpoints
public class OrderController {

    @Autowired
    private OrderService orderService;

    /**
     * Fetch full invoice/receipt details by the primary Order ID.
     */
    @GetMapping("/{id}")
    public ResponseEntity<OrderResponseDTO> getOrderDetails(@PathVariable Long id) {
        return ResponseEntity.ok(orderService.getOrderById(id));
    }

    /**
     * Retrieve the finalized order settlement generated by a specific auction session.
     */
    @GetMapping("/auction/{auctionId}")
    public ResponseEntity<OrderResponseDTO> getOrderByAuction(@PathVariable Long auctionId) {
        return ResponseEntity.ok(orderService.getOrderByAuctionId(auctionId));
    }

    /**
     * Get a comprehensive history of all orders won by a specific user using their username.
     */
    @GetMapping("/winner/{username}")
    public ResponseEntity<List<OrderResponseDTO>> getOrdersByWinner(@PathVariable String username) {
        return ResponseEntity.ok(orderService.getOrdersByWinnerUsername(username));
    }
}