package com.example.Auction_System.controller;

import com.example.Auction_System.dto.OrderResponseDTO;
import com.example.Auction_System.service.OrderService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/orders")
public class OrderController {

    private final OrderService orderService;

    public OrderController(OrderService orderService) {
        this.orderService = orderService;
    }

    /**
     * Fetch full invoice/receipt details by the primary Order ID.
     */
    @GetMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<OrderResponseDTO> getOrderDetails(@PathVariable Long id) {
        return ResponseEntity.ok(orderService.getOrderById(id));
    }

    /**
     * Retrieve the finalized order settlement generated by a specific auction session.
     */
    @GetMapping("/auction/{auctionId}")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<OrderResponseDTO> getOrderByAuction(@PathVariable Long auctionId) {
        return ResponseEntity.ok(orderService.getOrderByAuctionId(auctionId));
    }

    /**
     * Get a comprehensive history of all orders won by a specific user using their username.
     */
    @GetMapping("/winner/{username}")
    @PreAuthorize("hasAnyRole('ADMIN', 'BIDDER')")
    public ResponseEntity<List<OrderResponseDTO>> getOrdersByWinner(@PathVariable String username) {
        return ResponseEntity.ok(orderService.getOrdersByWinnerUsername(username));
    }

    @PostMapping("/{id}/pay")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<OrderResponseDTO> payOrder(@PathVariable Long id) {
        return ResponseEntity.ok(orderService.payOrder(id));
    }

    @GetMapping("/seller/{username}")
    @PreAuthorize("hasAnyRole('ADMIN', 'AUCTIONEER')")
    public ResponseEntity<List<OrderResponseDTO>> getOrdersBySeller(@PathVariable String username) {
        return ResponseEntity.ok(orderService.getOrdersBySellerUsername(username));
    }
}